[package]
name = "ether-test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"
ethers-solc = "2.0.14"
serde_json = "1.0.116"
